version: '3.9'
services:
  postgres:
    container_name: postgres
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: contra
      POSTGRES_DB: notesdb
    ports:
      - 5433:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: tomas@gmail.com
      PGADMIN_DEFAULT_PASSWORD: tomas
    ports:
      - '80:80'
    depends_on:
      - postgres
volumes:
  pg_data: